settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.f8fe94f2_64e2da92
    translate_unknown: Inconnu
    translate_idle: Inactif
    translate_home: Présent
    translate_not_home: Absent
    translate_available: disponible
    translate_no_updates: Aucune mise à jour
    translate_update_available: mise à jour disponible
    translate_updates_available: mises à jour disponibles
