homeassistant:
  name: ColonelFabien
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Paris
  currency: EUR
  country: FR
  packages: !include_dir_named packages
  # customize_domain:
      # initial_state: true
  # allowlist_external_dirs:
  #   - /config

default_config:
zeroconf:
wake_on_lan:
zha_toolkit:

frontend: !include themes.yaml
template: !include sidebar.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml

lovelace:
  mode: yaml
  resources:
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                             type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                      type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                           type: module },
      { url: /hacsfiles/button-card/button-card.js,                                     type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js?v=0.1.4,                           type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                            type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                      type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                                  type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,                type: module },
      { url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,      type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                       type: module },
      { url: /hacsfiles/weather-card/weather-card.js,                                   type: module },
      { url: /hacsfiles/upcoming-media-card/upcoming-media-card.js?v=0.1.2,             type: js },
      { url: /hacsfiles/clock-weather-card/clock-weather-card.js,                       type: module },
      { url: /hacsfiles/lovelace-buien-rain-card/buien-rain-card.js,                    type: module },
      { url: /hacsfiles/simple-thermostat/simple-thermostat.js,                         type: module },
      # { url: /hacsfiles/content-card-linky/content-card-linky.js,                       type: module },
      # { url: /hacsfiles/wiser/wiser-schedule-card.js,                                   type: module },
      # { url: /hacsfiles/wiser/wiser-zigbee-card.js,                                     type: module },
      # { url: /hacsfiles/history-explorer-card/history-explorer-card.js,                 type: module },
      # { url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js,             type: module },
      # { url: https://cdn.jsdelivr.net/gh/Imbuzi/meteo-france-weather-card/dist/meteo-france-weather-card.js,     type: module },
      { url: /hacsfiles/mini-climate-card/mini-climate-card-bundle.js?v=2.2.1,          type: module },
      { url: /hacsfiles/spotify-card/spotify-card.js,                                   type: module },
      { url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js,             type: js },
      { url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.16.4,         type: module },
      { url: /local/marked.min.js?v=4.1.0,                                              type: module },
      { url: /local/vanilla-tilt.min.js?v=1.7.2,                                        type: module },
      { url: /hacsfiles/scheduler-card/scheduler-card.js?v=0,                           type: module },
      { url: /local/fonts.css?v=2.1,                                                    type: css }
    ]

# Configuration de la base de donnée
# https://www.home-assistant.io/integrations/recorder/
recorder:
  purge_keep_days: 15 # Durée globale de conservation
  # commit_interval: 60 # Enregistrement toutes les 60 secondes
  auto_purge: true
  auto_repack: true
  include:
    domains:
      # - device_tracker
      # - media_player
      # - uptime
      # - time_date
      # - worldclock
      - light
    entity_globs:
      - climate.*
      - sensor.wiser*
      - switch.wiser*
      - sensor.*_summation_delivered*
      - sensor.*power*
      - sensor.*temperature*
      - sensor.*energy*
      - sensor.speedtest*
      - sensor.network_throughput_*
      - binary_sensor.trend_temp*

  #   entities:
  #     # - camera.front_door
  #     # - sensor.home_assistant_v2_db
  #     # - sensor.memory_free
  #     # - sensor.memory_use
  #     # - sensor.memory_use_percent
  #     # - sensor.processor_use
  #     # - weather.openweathermap
  # exclude:
  #   domains:
  #     - automation
  #     - updater
  #     - systemmonitor
  #     - Application mobile
  #     - Browser mod
  #     # - light
  #     - script
  #   entity_globs:
  #     - sensor.roberto.*
  #   entities:
  #     - sun.sun # Don't record sun data
  #     - sensor.last_boot # Comes from 'systemmonitor' sensor platform
  #     - sensor.date
  #   event_types:
  #     - call_service # Don't record service calls

zha:
  zigpy_config:
    network:
      channel: 11
      channels: [11]
    ota:
      otau_directory: /home/homeassistant/.homeassistant/config/zigpy_ota
      ikea_provider: false
      ledvance_provider: false
      salus_provider: false
      # ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json

spotcast:
  sp_dc: !secret stef_sp_dc
  sp_key: !secret stef_sp_key
  # country: FR #optional
  accounts:
    stef:
      sp_dc: !secret stef_sp_dc
      sp_key: !secret stef_sp_key
    # jo:
    #   sp_dc: !secret ming_sp_dc
    #   sp_key: !secret ming_sp_key

# logger:
#   default: info
#   logs:  
#     homeassistant.components.zha: debug
#     zigpy: debug