homekit:
  - ip_address: 127.0.0.1
    filter:
      include_entities:
        - light.lampe_boule
        - light.lampe_pixar
        - light.lampe_rouge
        - light.lumiere_de_la_chambre
        - light.lumiere_de_lentree
        - light.on_off_plug_1
        - light.spot_du_canape
        - light.spot_bleu
        - light.salon
        - sensor.hacs
        - scene.film
        - light.hue_white_lamp_1
        # - switch.deltaco_sh_p01_socket
        # - switch.imac
        # - switch.gosund_monitors_switch
        # - climate.ac
        # - switch.playstation_5
        # - switch.gosund_fan_switch
        # - person.matte
        # - person.sanja
        # - script.home_leave
        # - script.home_arrive
        # - script.samsung_tv_energy_saving
        # - vacuum.morty
        # - script.bedroom_tv_night
    entity_config:
      light.lampe_boule:
        name: Lampe boule
      light.lampe_pixar:
        name: Lampe Pixar
      light.lampe_rouge:
        name: Lumières du canapé
      light.lumiere_de_la_chambre:
        name: Lumière de la chambre
      light.lumiere_de_lentree:
        name: Lumière de l'entrée
      light.on_off_plug_1:
        name: Lumière du bar
      light.spot_du_canape:
        name: Spot du canapé
      light.spot_bleu:
        name: Spot bleu
      light.salon:
        name: Lumières du salon
      sensor.hacs:
        name: Capteur HACS
      scene.film:
        name: Film
      light.hue_white_lamp_1:
        name: Lumière inconnue
      # switch.deltaco_sh_p01_socket:
      #   name: Balkong
      # switch.computer_imac:
      #   name: Dator
      # switch.gosund_monitors_switch:
      #   name: Monitorer
      # climate.ac:
      #   name: Klimat
      # switch.playstation_5:
      #   name: Playstation
      # switch.gosund_fan_switch:
      #   name: Fläkt
      # person.matte:
      #   name: Mattias
      # person.sanja:
      #   name: Sanja
      # script.home_leave:
      #   name: Stäng allt
      # script.home_arrive:
      #   name: Hemma
      # script.samsung_tv_energy_saving:
      #   name: Eko
      # vacuum.morty:
      #   name: Morty
      # script.bedroom_tv_night:
      #   name: Nattläge

  # - name: HASS Bridge Sony
  #   ip_address: !secret nas_host
  #   port: 51828
  #   mode: accessory
  #   filter:
  #     include_entities:
  #       - media_player.sony_bravia_tv
  #   entity_config:
  #     media_player.sony_bravia_tv:
  #       name: Sony TV
  #       feature_list:
  #         - feature: on_off

  # - name: HASS Bridge Samsung
  #   ip_address: !secret nas_host
  #   port: 51829
  #   mode: accessory
  #   filter:
  #     include_entities:
  #       - media_player.samsung
  #   entity_config:
  #     media_player.samsung:
  #       name: Samsung TV
  #       feature_list:
  #         - feature: on_off
