sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /filer
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: network_in
        arg: eno1
      - type: network_out
        arg: eno1
      - type: throughput_network_in
        arg: eno1
      - type: throughput_network_out
        arg: eno1
      - type: network_in
        arg: wg0
      - type: network_out
        arg: wg0
      - type: throughput_network_in
        arg: wg0
      - type: throughput_network_out
        arg: wg0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: ipv4_address
        arg: eno1
      - type: ipv4_address
        arg: wg0

  - platform: bbox
    monitored_variables:
      - down_max_bandwidth
      - up_max_bandwidth
      - current_down_bandwidth
      - current_up_bandwidth
      - uptime
      - number_of_reboots

  # https://github.com/NemesisRE/sensor.plex_recently_added
  - platform: plex_recently_added
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    img_dir: /
    # on_deck: true
    image_resolution: 800

  - platform: plex_recently_added
    name: Plex Recently Show Added
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    img_dir: /
    image_resolution: 800
    section_types:
      - show

  - platform: plex_recently_added
    name: Plex Recently Movie Added
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    img_dir: /
    image_resolution: 800
    section_types:
      - movie

samsungtv:
  - host: !secret tv_ip
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret tv_mac
    app_list:
     '{"Plex": "kIciSQlYEM.plex","Netflix": "11101200001", "YouTubeTV": " PvWgqxV3Xa.YouTubeTV"}'

media_player:
  - platform: samsungtv_tizen
    name: samsung_tv_salon
    # device_id: 47f56a24-c389-4ea4-84d0-01c4af42abd8
    host: 192.168.1.57
    mac: 9c:8c:6e:29:3a:30
    # api_key: 4c8ba490-fe54-4362-aeeb-cae76327d808
    # update_method: smartthings
    # turn_on_action:
    #   service: wake_on_lan.send_magic_packet
    #   data:
    #     mac: 9c:8c:6e:29:3a:30
    # app_list:
    #  '{"Plex": "kIciSQlYEM.plex","Netflix": "11101200001", "YouTubeTV": " PvWgqxV3Xa.YouTubeTV"}'

climate:
  - platform: generic_thermostat
    name: Bureau
    heater: climate.actionneur_chauffage_thermostat
    target_sensor: sensor.hue_motion_sensor_1_temperature_2

# switch:
#   - platform: wake_on_lan
#     mac: !secret tv_mac

#   - platform: template
#     switches:
#       netflix:
#         friendly_name: "Netflix"
#         value_template: >-
#           "{{ is_state_attr('media_player.samsung_6_series_43', 'source', 'Netflix') }}"
#         icon_template: mdi:netflix
#         turn_on:
#           service: media_player.select_source
#           data:
#             entity_id: media_player.samsung_6_series_43
#             source: "Netflix"
#         turn_off:
#           service: media_player.select_source
#           data:
#             entity_id: media_player.samsung_6_series_43
#             source: "TV"

device_tracker:
  - platform: bbox

binary_sensor:
  - platform: ping
    name: internet_ping
    host: !secret internet_ping_test
    scan_interval: 15

  - platform: ping
    name: vpn_stef_iphone_perso
    host: !secret network_vpn_stef_iphone_xr
    scan_interval: 15

  - platform: ping
    name: vpn_stef_iphone_pro
    host: !secret network_vpn_stef_iphone_pro
    scan_interval: 15

  - platform: ping
    name: vpn_stef_macbook
    host: !secret network_vpn_stef_macbook
    scan_interval: 15

  - platform: ping
    name: vpn_sonia
    host: !secret network_vpn_sonia
    scan_interval: 15

# template:
#   - sensor:
#       - unique_id: nas_status
#         state: >
#           {% set entity_id = 'sensor.nas_volume_1_status' %}
#           {% if is_state(entity_id, 'normal') %}
#             Bra
#           {% elif is_state(entity_id, 'background_scrubbing') %}
#             Dataskrubbning
#           {% else %}
#             {{ states(entity_id) }}
#           {% endif %}
#         attributes:
#           friendly_name: Systemhälsa
#           icon: cil:synology-nas

#       - unique_id: domain_counter
#         state: >
#           {{ states | count }}
#         attributes:
#           automation: >
#             {{ states.automation | count }}
#           binary_sensor: >
#             {{ states.binary_sensor | count }}
#           device_tracker: >
#             {{ states.device_tracker | count }}
#           light: >
#             {{ states.light | count }}
#           media_player: >
#             {{ states.media_player | count }}
#           sensor: >
#             {{ states.sensor | count }}
#           switch: >
#             {{ states.switch | count }}
#           other: >
#             {% set exclude = this.attributes | list %}
#             {{ states | rejectattr('domain', 'in', exclude) | list | count }}

# shell_command:
#   restart_container: !secret restart_container
#   purge_log: truncate -s 0 /config/home-assistant.log

# https://github.com/ualex73/monitor_docker
# monitor_docker:
#   - name: Docker
#     containers:
#       - watchtower
#       - home-assistant
#       - transmission-seed
#     monitored_conditions: allinone
#     scan_interval: 900

# automation:
#   - alias: purge_log_filesize
#     id: '3331821824310'
#     trigger:
#       platform: numeric_state
#       entity_id: sensor.home_assistant_log_size
#       above: 50
#     action:
#       service: shell_command.purge_log
